name: Crear Estructura de Curs

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositori
        uses: actions/checkout@v4

      - name: Crear carpetes i fitxers .gitkeep
        run: |
          mkdir -p M5071_Models_IA/{Apunts,Practiques}
          mkdir -p M5072_Aprenentatge_Automatic/{Apunts,Practiques}
          mkdir -p M5073_Programacio_IA/{Apunts,Practiques}
          mkdir -p M5074_Sistemes_BigData/{Apunts,Practiques}
          mkdir -p M5075_BigData_Aplicat/{Apunts,Practiques}
          mkdir -p C088_Projecte/Documentacio
          find . -type d -empty -exec touch {}/.gitkeep \;

      - name: Guardar canvis a GitHub
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Estructura automatitzada de mòduls" || exit 0
          git push
